# Generated by Django 3.1.7 on 2021-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210517_2209'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='wholesale_variants',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to='product.WholesaleProductVariant'),
        ),
    ]
