# Generated by Django 3.2.4 on 2021-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210621_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores'),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
