# Generated by Django 3.1.7 on 2021-05-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=150)),
                ('host', models.CharField(max_length=150)),
                ('request_method', models.CharField(max_length=150)),
                ('user_agent', models.CharField(max_length=150)),
            ],
        ),
    ]
