# Generated by Django 3.1.7 on 2021-03-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wholesaleproductvariant",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wholesale_products",
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="wholesaleproductvariant",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wholesale_products",
                to="product.variation",
            ),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="product.productimage",
            ),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="product.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="images",
            field=models.ManyToManyField(
                through="product.VariantImage", to="product.ProductImage"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="product.variation",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="product.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="customizations",
            field=models.ManyToManyField(to="product.Customization"),
        ),
        migrations.AddField(
            model_name="product",
            name="default_variant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="product.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.producttype",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="variations",
            field=models.ManyToManyField(to="product.Variation"),
        ),
        migrations.AddField(
            model_name="collectionproduct",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionproduct",
                to="product.collection",
            ),
        ),
        migrations.AddField(
            model_name="collectionproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionproduct",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="product.CollectionProduct",
                to="product.Product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wholesalevariantimage",
            unique_together={("variant", "image")},
        ),
        migrations.AlterUniqueTogether(
            name="variantimage",
            unique_together={("variant", "image")},
        ),
        migrations.AlterUniqueTogether(
            name="collectionproduct",
            unique_together={("collection", "product")},
        ),
    ]
