# Generated by Django 3.1.7 on 2021-03-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20210326_2122"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="product",
        ),
    ]
