# Generated by Django 3.1.7 on 2021-04-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productreview_productreviewfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
