# Generated by Django 3.1.7 on 2021-04-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210406_1852'),
        ('product', '0003_remove_productvariant_product'),
    ]

    operations = [
    ]
