# Generated by Django 3.1.7 on 2021-06-10 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_auto_20210610_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(through='room.RoomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
