# Generated by Django 3.2.4 on 2021-07-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roomrecommendedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='media/Message'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_users', to='room.room'),
        ),
    ]
