# Generated by Django 3.1.7 on 2021-03-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('pk',), 'verbose_name': 'Payment'},
        ),
    ]
