# Generated by Django 3.1.7 on 2021-04-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210412_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
