# Generated by Django 3.1.7 on 2021-05-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtraffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Rejected')], max_length=5),
        ),
    ]
