# Generated by Django 3.1.7 on 2021-06-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210517_2209'),
        ('shop', '0002_auto_20210601_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='wholesale_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='product.wholesaleproductvariant'),
        ),
    ]
